#!/usr/bin/env rake

task :default => [:lint, :html]

DISABLED = ['conway.*', 'astar.*']

jade_file = 'layout.jade'
json_files = FileList['*.json']
html_files = json_files.ext('html')

json_files.each { |src|
	html = src.ext('html')
	file html => jade_file
	file html => src do |f|
		sh "jade --pretty --obj #{src} #{jade_file}"
		sh "mv #{jade_file.ext('html')} #{html}"
	end
}

#rule ".html" => ".jade" do |t| sh "jade --pretty #{t.source}"  	end
#rule ".css"  => ".less" do |t| sh "lessc #{t.source} #{t.name}"	end

desc 'Generate all HTML files'
task :html => html_files

desc 'Lint JS(ON)? files'
task :lint do
	FileList['*.js', '*.json'].exclude(*DISABLED).each do |src|
		sh "jshint #{src}"
	end
end

require 'rake/clean'
CLOBBER.include(html_files) # .include('.css')
